export type ProductLine = 'laser-sensors' | 'fixed-scanners' | 'scan-modules' | 'handheld-scanners';

export interface ProductSpec {
  label: string;
  value: string;
}

export interface Product {
  id: string;
  model: string;
  name: { en: string; ko: string; 'zh-TW': string; de: string; fr: string; it: string; es: string };
  tagline: { en: string; ko: string; 'zh-TW': string; de: string; fr: string; it: string; es: string };
  description: { en: string; ko: string; 'zh-TW': string; de: string; fr: string; it: string; es: string };
  features: { en: string[]; ko: string[]; 'zh-TW': string[]; de: string[]; fr: string[]; it: string[]; es: string[] };
  specs: ProductSpec[];
  image: string;
  accentColor: string;
}

export interface ProductLineData {
  id: ProductLine;
  name: { en: string; ko: string; 'zh-TW': string; de: string; fr: string; it: string; es: string };
  tagline: { en: string; ko: string; 'zh-TW': string; de: string; fr: string; it: string; es: string };
  heroImage: string;
  products: Product[];
  applications: { en: ApplicationItem[]; ko: ApplicationItem[]; 'zh-TW': ApplicationItem[]; de: ApplicationItem[]; fr: ApplicationItem[]; it: ApplicationItem[]; es: ApplicationItem[] };
  showWhyLaser?: boolean;
}

export interface ApplicationItem {
  title: string;
  description: string;
  icon: string;
}

export const productLines: ProductLineData[] = [
  {
    id: 'laser-sensors',
    showWhyLaser: true,
    name: {
      en: 'Laser Sensors',
      ko: '레이저 센서',
      'zh-TW': '雷射感測器',
      de: 'Lasersensoren',
      fr: 'Capteurs Laser',
      it: 'Sensori Laser',
      es: 'Sensores Láser',
    },
    tagline: {
      en: 'Precision sensing beyond limits.',
      ko: '한계를 초월한 정밀 감지.',
      'zh-TW': '突破極限的精密感測。',
      de: 'Präzisionssensorik ohne Grenzen.',
      fr: 'Détection de précision sans limites.',
      it: 'Rilevamento di precisione senza limiti.',
      es: 'Detección de precisión sin límites.',
    },
    heroImage: '/images/products/zx-td0200n-sheet.png',
    products: [
      {
        id: 'zx-pe0040n',
        model: 'ZX-PE0040N',
        name: {
          en: 'Laser Sensor',
          ko: '레이저 센서',
          'zh-TW': '雷射感測器',
          de: 'Lasersensor',
          fr: 'Capteur Laser',
          it: 'Sensore Laser',
          es: 'Sensor Láser',
        },
        tagline: {
          en: 'Ultra-precise point detection at 40mm.',
          ko: '40mm에서의 초정밀 포인트 감지.',
          'zh-TW': '40mm 超精密點感測。',
          de: 'Ultrapräzise Punkterkennung bei 40mm.',
          fr: 'Détection de point ultra-précise à 40mm.',
          it: 'Rilevamento puntuale ultra-preciso a 40mm.',
          es: 'Detección puntual ultraprecisa a 40mm.',
        },
        description: {
          en: 'The ZX-PE0040N photoelectric sensor delivers pinpoint 0.1mm spot accuracy at its rated 40mm detection range. Built for high-density component detection on PCB lines and precision assembly systems.',
          ko: 'ZX-PE0040N 광전 센서는 40mm 정격 감지 거리에서 0.1mm 스팟 정밀도를 제공합니다. PCB 라인과 정밀 조립 시스템에서의 고밀도 부품 감지를 위해 설계되었습니다.',
          'zh-TW': 'ZX-PE0040N 光電感測器在 40mm 額定偵測距離下提供精準的 0.1mm 光點精度。專為 PCB 生產線和精密組裝系統上的高密度元件偵測所設計。',
          de: 'Der ZX-PE0040N Photoelektriksensor liefert punktgenaue 0,1mm Spotpräzision bei 40mm Erfassungsreichweite. Entwickelt für hochdichte Bauteilerkennung auf PCB-Linien und präzisen Montagesystemen.',
          fr: 'Le capteur photoélectrique ZX-PE0040N offre une précision de spot de 0,1mm à sa portée de détection nominale de 40mm. Conçu pour la détection de composants haute densité sur les lignes PCB et les systèmes d\'assemblage de précision.',
          it: 'Il sensore fotoelettrico ZX-PE0040N offre una precisione del punto di 0,1mm alla sua portata di rilevamento nominale di 40mm. Progettato per il rilevamento di componenti ad alta densità su linee PCB e sistemi di assemblaggio di precisione.',
          es: 'El sensor fotoeléctrico ZX-PE0040N ofrece una precisión de punto de 0,1mm en su alcance de detección nominal de 40mm. Diseñado para la detección de componentes de alta densidad en líneas PCB y sistemas de ensamblaje de precisión.',
        },
        features: {
          en: [
            'IEC standard photoelectric sensing',
            '0.1mm ultra-fine spot at 40mm distance',
            'Laser Red 650nm, Class 2 — safe & precise',
            '< 1ms response time for high-speed lines',
            'IP66 protection — dust-tight & jet-water resistant',
            'Operating range: −10°C to 55°C',
          ],
          ko: [
            'IEC 표준 광전 감지',
            '40mm 거리에서 0.1mm 초미세 스팟',
            '레이저 레드 650nm, Class 2 — 안전하고 정밀함',
            '고속 라인을 위한 < 1ms 응답 시간',
            'IP66 보호 — 방진 및 방수젯',
            '작동 범위: −10°C ~ 55°C',
          ],
          'zh-TW': [
            'IEC 標準光電感測',
            '40mm 距離下 0.1mm 超細光點',
            '雷射紅光 650nm，Class 2 — 安全且精確',
            '< 1ms 響應時間，適用於高速生產線',
            'IP66 防護 — 防塵且耐水柱噴射',
            '工作範圍：−10°C 至 55°C',
          ],
          de: [
            'IEC-Standard Photoelektrik-Sensorik',
            '0,1mm Ultrafeinpunkt bei 40mm Entfernung',
            'Laser Rot 650nm, Klasse 2 — sicher & präzise',
            '< 1ms Reaktionszeit für Hochgeschwindigkeitslinien',
            'IP66-Schutz — staubdicht & wasserstrahlbeständig',
            'Betriebstemperatur: −10°C bis 55°C',
          ],
          fr: [
            'Détection photoélectrique standard IEC',
            'Spot ultra-fin de 0,1mm à 40mm de distance',
            'Laser Rouge 650nm, Classe 2 — sûr & précis',
            '< 1ms de temps de réponse pour les lignes à grande vitesse',
            'Protection IP66 — étanche à la poussière & résistant aux jets d\'eau',
            'Plage de fonctionnement : −10°C à 55°C',
          ],
          it: [
            'Rilevamento fotoelettrico standard IEC',
            'Punto ultra-fine da 0,1mm a 40mm di distanza',
            'Laser Rosso 650nm, Classe 2 — sicuro & preciso',
            '< 1ms di tempo di risposta per linee ad alta velocità',
            'Protezione IP66 — a tenuta di polvere & resistente ai getti d\'acqua',
            'Intervallo operativo: −10°C a 55°C',
          ],
          es: [
            'Detección fotoeléctrica estándar IEC',
            'Punto ultrafino de 0,1mm a 40mm de distancia',
            'Láser Rojo 650nm, Clase 2 — seguro y preciso',
            '< 1ms de tiempo de respuesta para líneas de alta velocidad',
            'Protección IP66 — a prueba de polvo y resistente a chorros de agua',
            'Rango de operación: −10°C a 55°C',
          ],
        },
        specs: [
          { label: 'Working Principle', value: 'Photoelectric Sensor' },
          { label: 'Detection Range', value: '40 mm' },
          { label: 'Light Source', value: 'Laser Red 650nm, Class 2' },
          { label: 'Spot Size', value: '~0.1mm @ 40mm' },
          { label: 'Sensitivity', value: '8-turn potentiometer' },
          { label: 'Response Time', value: '< 1 ms' },
          { label: 'Operating Temp', value: '−10°C to 55°C' },
          { label: 'Protection', value: 'IP66' },
        ],
        image: '/images/products/zx-pe0040n.png',
        accentColor: '#D4192C',
      },
      {
        id: 'zx-td0200n',
        model: 'ZX-TD0200N',
        name: {
          en: 'TOF Laser Sensor',
          ko: 'TOF 레이저 센서',
          'zh-TW': 'TOF 雷射感測器',
          de: 'TOF-Lasersensor',
          fr: 'Capteur Laser TOF',
          it: 'Sensore Laser TOF',
          es: 'Sensor Láser TOF',
        },
        tagline: {
          en: 'Time-of-Flight precision up to 2000mm.',
          ko: '2000mm까지의 비행 시간 정밀도.',
          'zh-TW': '飛行時間精度達 2000mm。',
          de: 'Time-of-Flight-Präzision bis 2000mm.',
          fr: 'Précision Time-of-Flight jusqu\'à 2000mm.',
          it: 'Precisione Time-of-Flight fino a 2000mm.',
          es: 'Precisión Time-of-Flight hasta 2000mm.',
        },
        description: {
          en: 'The ZX-TD0200N uses Time-of-Flight (TOF) technology to deliver reliable detection across multi-material, multi-color targets up to 2 meters away — where LED sensors fail. Perfect for conveyor height checks, pallet sensing, and AGV applications.',
          ko: 'ZX-TD0200N은 비행 시간(TOF) 기술을 사용하여 최대 2미터 떨어진 다중 재질, 다중 색상 목표에 걸쳐 신뢰할 수 있는 감지를 제공합니다. 컨베이어 높이 확인, 팔레트 감지, AGV 응용 프로그램에 적합합니다.',
          'zh-TW': 'ZX-TD0200N 採用飛行時間（TOF）技術，在最遠 2 公尺距離的多材質、多顏色目標上提供可靠偵測——這是 LED 感測器無法做到的。完美適用於輸送帶高度檢查、棧板感測和 AGV 應用。',
          de: 'Der ZX-TD0200N nutzt Time-of-Flight (TOF)-Technologie für zuverlässige Erkennung an multi-material, mehrfarbigen Zielen bis zu 2 Meter Entfernung — wo LED-Sensoren versagen. Ideal für Förderbandhöhenprüfung, Palettenerfassung und AGV-Anwendungen.',
          fr: 'Le ZX-TD0200N utilise la technologie Time-of-Flight (TOF) pour offrir une détection fiable sur des cibles multi-matériaux et multicolores jusqu\'à 2 mètres — là où les capteurs LED échouent. Idéal pour le contrôle de hauteur des convoyeurs, la détection de palettes et les applications AGV.',
          it: 'Il ZX-TD0200N utilizza la tecnologia Time-of-Flight (TOF) per offrire un rilevamento affidabile su bersagli multi-materiale e multicolore fino a 2 metri — dove i sensori LED falliscono. Perfetto per il controllo dell\'altezza dei nastri trasportatori, il rilevamento di pallet e le applicazioni AGV.',
          es: 'El ZX-TD0200N utiliza la tecnología Time-of-Flight (TOF) para ofrecer una detección fiable en objetivos de múltiples materiales y colores hasta 2 metros — donde los sensores LED fallan. Perfecto para verificación de altura en cintas transportadoras, detección de palés y aplicaciones AGV.',
        },
        features: {
          en: [
            'TOF (Time-of-Flight) principle — material & color independent',
            'Detection range: 100–2000 mm',
            'Spot size: 5mm @ 200mm — focused beam',
            '< 1ms response for real-time control',
            'IP64 protection — industrial-grade',
            'Operating: −10°C to 55°C (No Freezing)',
            'Light Source: Laser Red 650nm, Class 2',
          ],
          ko: [
            'TOF (비행 시간) 원리 — 재질 및 색상 독립적',
            '감지 범위: 100–2000 mm',
            '스팟 크기: 200mm에서 5mm — 집중 빔',
            '실시간 제어를 위한 < 1ms 응답',
            'IP64 보호 — 산업용 등급',
            '작동: −10°C ~ 55°C (동결 없음)',
            '광원: 레이저 레드 650nm, Class 2',
          ],
          'zh-TW': [
            'TOF（飛行時間）原理 — 與材質和顏色無關',
            '偵測範圍：100–2000 mm',
            '光點大小：200mm 處 5mm — 聚焦光束',
            '< 1ms 響應，用於實時控制',
            'IP64 防護 — 工業級別',
            '工作溫度：−10°C 至 55°C（無冷凍）',
            '光源：雷射紅光 650nm，Class 2',
          ],
          de: [
            'TOF (Time-of-Flight)-Prinzip — material- und farb-unabhängig',
            'Erfassungsbereich: 100–2000 mm',
            'Spotgröße: 5mm @ 200mm — fokussierter Strahl',
            '< 1ms Reaktion für Echtzeit-Steuerung',
            'IP64-Schutz — industrietauglich',
            'Betrieb: −10°C bis 55°C (kein Einfrieren)',
            'Lichtquelle: Laser Rot 650nm, Klasse 2',
          ],
          fr: [
            'Principe TOF (Time-of-Flight) — indépendant du matériau et de la couleur',
            'Portée de détection : 100–2000 mm',
            'Taille du spot : 5mm @ 200mm — faisceau focalisé',
            '< 1ms de réponse pour le contrôle en temps réel',
            'Protection IP64 — qualité industrielle',
            'Fonctionnement : −10°C à 55°C (sans gel)',
            'Source lumineuse : Laser Rouge 650nm, Classe 2',
          ],
          it: [
            'Principio TOF (Time-of-Flight) — indipendente dal materiale e dal colore',
            'Portata di rilevamento: 100–2000 mm',
            'Dimensione del punto: 5mm @ 200mm — fascio focalizzato',
            '< 1ms di risposta per il controllo in tempo reale',
            'Protezione IP64 — grado industriale',
            'Funzionamento: −10°C a 55°C (senza congelamento)',
            'Sorgente luminosa: Laser Rosso 650nm, Classe 2',
          ],
          es: [
            'Principio TOF (Time-of-Flight) — independiente del material y color',
            'Alcance de detección: 100–2000 mm',
            'Tamaño del punto: 5mm @ 200mm — haz enfocado',
            '< 1ms de respuesta para control en tiempo real',
            'Protección IP64 — calidad industrial',
            'Funcionamiento: −10°C a 55°C (sin congelamiento)',
            'Fuente de luz: Láser Rojo 650nm, Clase 2',
          ],
        },
        specs: [
          { label: 'Working Principle', value: 'TOF (Time to Flight)' },
          { label: 'Detection Range', value: '100 ~ 2000 mm' },
          { label: 'Light Source', value: 'Laser Red 650nm, Class 2' },
          { label: 'Spot Size', value: '5mm @ 200mm' },
          { label: 'Response Time', value: '< 1 ms' },
          { label: 'Button', value: 'Button Setting' },
          { label: 'Operating Temp', value: '−10°C to 55°C' },
          { label: 'Protection', value: 'IP64' },
        ],
        image: '/images/products/zx-td0200n.png',
        accentColor: '#D4192C',
      },
    ],
    applications: {
      en: [
        {
          title: 'Conveyor Belt Monitoring',
          description: 'Detect package height, presence, and gaps on high-speed conveyor lines without false triggers from belt surfaces or ambient light.',
          icon: '🏭',
        },
        {
          title: 'AGV & Robot Navigation',
          description: 'Provide precise distance feedback for autonomous guided vehicles and robotic arms requiring reliable obstacle detection up to 2 meters.',
          icon: '🤖',
        },
        {
          title: 'PCB Component Inspection',
          description: 'Ultra-fine 0.1mm spot size enables detection of micro-components on circuit boards — critical for surface-mount technology lines.',
          icon: '🔬',
        },
        {
          title: 'Pallet & Rack Sensing',
          description: 'Confirm pallet presence and positioning in warehouse racking systems, with color-independent TOF sensing for all pallet materials.',
          icon: '📦',
        },
      ],
      ko: [
        {
          title: '컨베이어 벨트 모니터링',
          description: '벨트 표면이나 주변광의 오작동 없이 고속 컨베이어 라인에서 패키지 높이, 존재 여부 및 간격을 감지합니다.',
          icon: '🏭',
        },
        {
          title: 'AGV 및 로봇 내비게이션',
          description: '최대 2미터까지 신뢰할 수 있는 장애물 감지가 필요한 자율 유도 차량 및 로봇 팔에 정확한 거리 피드백을 제공합니다.',
          icon: '🤖',
        },
        {
          title: 'PCB 부품 검사',
          description: '0.1mm 초미세 스팟 크기로 회로 기판의 마이크로 부품 감지 가능 — 표면 실장 기술 라인에 필수적입니다.',
          icon: '🔬',
        },
        {
          title: '팔레트 및 랙 감지',
          description: '모든 팔레트 재질에 대한 색상 독립적 TOF 감지로 창고 선반 시스템에서 팔레트 존재 및 위치를 확인합니다.',
          icon: '📦',
        },
      ],
      'zh-TW': [
        {
          title: '輸送帶監控',
          description: '在高速輸送帶生產線上偵測包裝高度、存在情況和間隙，不受皮帶表面或環境光線的誤觸發影響。',
          icon: '🏭',
        },
        {
          title: 'AGV 和機器人導航',
          description: '為需要可靠障礙物偵測（最遠 2 公尺）的自主導引車和機械臂提供精確的距離回饋。',
          icon: '🤖',
        },
        {
          title: 'PCB 元件檢測',
          description: '超細 0.1mm 光點大小，可偵測電路板上的微型元件——對於表面貼裝技術生產線至關重要。',
          icon: '🔬',
        },
        {
          title: '棧板和貨架感測',
          description: '以與顏色無關的 TOF 感測確認倉庫貨架系統中所有棧板材質的棧板存在和定位。',
          icon: '📦',
        },
      ],
      de: [
        {
          title: 'Förderband-Überwachung',
          description: 'Erkennen Sie Pakethöhe, Präsenz und Lücken auf Hochgeschwindigkeits-Förderbandlinien ohne Fehlauslösungen durch Bandoberflächen oder Umgebungslicht.',
          icon: '🏭',
        },
        {
          title: 'AGV & Roboternavigation',
          description: 'Präzises Entfernungsfeedback für autonome Transportfahrzeuge und Roboterarme mit zuverlässiger Hinderniserkennung bis zu 2 Metern.',
          icon: '🤖',
        },
        {
          title: 'PCB-Bauteilprüfung',
          description: 'Ultrafeine 0,1mm Spotgröße ermöglicht Erkennung von Mikrobauteilen auf Leiterplatten — entscheidend für SMT-Linien.',
          icon: '🔬',
        },
        {
          title: 'Paletten- & Regalsensorik',
          description: 'Palettenvorhandensein und -positionierung in Lagerregalanlagen bestätigen mit farb-unabhängiger TOF-Sensorik für alle Palettenmaterialien.',
          icon: '📦',
        },
      ],
      fr: [
        { title: 'Surveillance des Convoyeurs', description: 'Détectez la hauteur, la présence et les espaces des colis sur les lignes de convoyeurs à grande vitesse sans faux déclenchements dus aux surfaces des courroies ou à la lumière ambiante.', icon: '🏭' },
        { title: 'Navigation AGV & Robotique', description: 'Fournissez un retour de distance précis pour les véhicules à guidage autonome et les bras robotiques nécessitant une détection d\'obstacles fiable jusqu\'à 2 mètres.', icon: '🤖' },
        { title: 'Inspection de Composants PCB', description: 'La taille de spot ultra-fine de 0,1mm permet la détection de micro-composants sur les circuits imprimés — essentiel pour les lignes de technologie de montage en surface.', icon: '🔬' },
        { title: 'Détection de Palettes & Étagères', description: 'Confirmez la présence et le positionnement des palettes dans les systèmes de rayonnage d\'entrepôt, avec une détection TOF indépendante de la couleur pour tous les matériaux de palette.', icon: '📦' },
      ],
      it: [
        { title: 'Monitoraggio Nastri Trasportatori', description: 'Rilevate altezza, presenza e spazi dei pacchi su linee di trasporto ad alta velocità senza falsi trigger da superfici del nastro o luce ambientale.', icon: '🏭' },
        { title: 'Navigazione AGV & Robot', description: 'Fornite feedback di distanza preciso per veicoli a guida automatica e bracci robotici che richiedono un rilevamento affidabile degli ostacoli fino a 2 metri.', icon: '🤖' },
        { title: 'Ispezione Componenti PCB', description: 'La dimensione del punto ultra-fine di 0,1mm consente il rilevamento di micro-componenti su circuiti stampati — critico per le linee di tecnologia SMT.', icon: '🔬' },
        { title: 'Rilevamento Pallet & Scaffali', description: 'Confermate la presenza e il posizionamento dei pallet nei sistemi di scaffalatura di magazzino, con rilevamento TOF indipendente dal colore per tutti i materiali dei pallet.', icon: '📦' },
      ],
      es: [
        { title: 'Monitoreo de Cintas Transportadoras', description: 'Detecte altura, presencia y espacios de paquetes en líneas de cinta transportadora de alta velocidad sin falsos disparos por superficies de correa o luz ambiental.', icon: '🏭' },
        { title: 'Navegación AGV y Robótica', description: 'Proporcione retroalimentación de distancia precisa para vehículos de guía autónoma y brazos robóticos que requieren detección fiable de obstáculos hasta 2 metros.', icon: '🤖' },
        { title: 'Inspección de Componentes PCB', description: 'El tamaño de punto ultrafino de 0,1mm permite la detección de micro-componentes en circuitos impresos — crítico para líneas de tecnología de montaje superficial.', icon: '🔬' },
        { title: 'Detección de Palés y Estanterías', description: 'Confirme la presencia y posicionamiento de palés en sistemas de estanterías de almacén, con detección TOF independiente del color para todos los materiales de palé.', icon: '📦' },
      ],
    },
  },

  {
    id: 'fixed-scanners',
    name: {
      en: 'Fixed Industrial Scanners',
      ko: '고정형 산업용 스캐너',
      'zh-TW': '固定式工業掃描器',
      de: 'Stationäre Industriescanner',
      fr: 'Scanners Industriels Fixes',
      it: 'Scanner Industriali Fissi',
      es: 'Escáneres Industriales Fijos',
    },
    tagline: {
      en: 'Always-on intelligence for automated lines.',
      ko: '자동화 라인을 위한 상시 작동 인텔리전스.',
      'zh-TW': '自動化生產線的持續智慧監控。',
      de: 'Dauerbetrieb-Intelligenz für automatisierte Linien.',
      fr: 'Intelligence permanente pour les lignes automatisées.',
      it: 'Intelligenza sempre attiva per le linee automatizzate.',
      es: 'Inteligencia permanente para líneas automatizadas.',
    },
    heroImage: '/images/products/zx-3020-sheet.png',
    products: [
      {
        id: 'zx-1060',
        model: 'ZX-1060',
        name: {
          en: '2D Image Fixed Industrial Scanner',
          ko: '2D 이미지 고정형 산업용 스캐너',
          'zh-TW': '2D 影像固定式工業掃描器',
          de: '2D-Bild-Stationär-Industriescanner',
          fr: 'Scanner Industriel Fixe à Image 2D',
          it: 'Scanner Industriale Fisso a Immagine 2D',
          es: 'Escáner Industrial Fijo de Imagen 2D',
        },
        tagline: {
          en: 'Fast, precise, and drop-proof.',
          ko: '빠르고, 정밀하며, 낙하 방지.',
          'zh-TW': '快速、精確且防摔。',
          de: 'Schnell, präzise und sturzsicher.',
          fr: 'Rapide, précis et résistant aux chutes.',
          it: 'Veloce, preciso e resistente alle cadute.',
          es: 'Rápido, preciso y resistente a caídas.',
        },
        description: {
          en: 'The ZX-1060 delivers real-time solutions with fast, precise focusing for high-throughput automation lines. IP67-rated and validated to survive 1.8m drops, it thrives in demanding factory environments where uptime is non-negotiable.',
          ko: 'ZX-1060은 고처리량 자동화 라인을 위해 빠르고 정밀한 포커싱으로 실시간 솔루션을 제공합니다. IP67 등급이며 1.8m 낙하를 견딜 수 있어, 가동 시간이 필수적인 까다로운 공장 환경에서 활약합니다.',
          'zh-TW': 'ZX-1060 為高吞吐量自動化生產線提供具有快速精準對焦的即時解決方案。IP67 等級，經驗證可承受 1.8m 跌落，在對停機時間要求嚴格的惡劣工廠環境中表現卓越。',
          de: 'Der ZX-1060 liefert Echtzeit-Lösungen mit schneller, präziser Fokussierung für Hochdurchsatz-Automatisierungslinien. IP67-zertifiziert und für 1,8m-Stürze validiert, bewährt er sich in anspruchsvollen Fabrikumgebungen.',
          fr: 'Le ZX-1060 offre des solutions en temps réel avec une mise au point rapide et précise pour les lignes d\'automatisation à haut débit. Certifié IP67 et validé pour résister à des chutes de 1,8m, il excelle dans les environnements d\'usine exigeants où les arrêts de production ne sont pas tolérés.',
          it: 'Il ZX-1060 offre soluzioni in tempo reale con messa a fuoco rapida e precisa per linee di automazione ad alto rendimento. Certificato IP67 e validato per resistere a cadute di 1,8m, eccelle negli ambienti di fabbrica più esigenti dove i fermi produzione non sono tollerati.',
          es: 'El ZX-1060 ofrece soluciones en tiempo real con enfoque rápido y preciso para líneas de automatización de alto rendimiento. Con certificación IP67 y validado para resistir caídas de 1,8m, rinde al máximo en entornos de fábrica exigentes donde el tiempo de inactividad no es una opción.',
        },
        features: {
          en: [
            'Real-time fast, precise auto-focus',
            'Withstands 1.8m multiple drop tests',
            'IP67 — dust-tight & full water immersion',
            'Advanced DPM (Direct Part Marking) decoding',
            'Modbus, Ethernet/IP, PROFINET support',
            'USB-A & WiFi Auto-Forward connectivity',
          ],
          ko: [
            '실시간 빠르고 정밀한 자동 포커스',
            '1.8m 다중 낙하 테스트 통과',
            'IP67 — 방진 및 완전 방수',
            '고급 DPM (직접 부품 마킹) 디코딩',
            'Modbus, Ethernet/IP, PROFINET 지원',
            'USB-A 및 WiFi Auto-Forward 연결',
          ],
          'zh-TW': [
            '即時快速精準自動對焦',
            '承受 1.8m 多次跌落測試',
            'IP67 — 防塵且完全防水浸泡',
            '先進的 DPM（直接零件標記）解碼',
            '支援 Modbus、Ethernet/IP、PROFINET',
            'USB-A 和 WiFi 自動轉發連線',
          ],
          de: [
            'Echtzeit schneller, präziser Autofokus',
            'Übersteht 1,8m Mehrfach-Sturztests',
            'IP67 — staubdicht & vollständige Wassertauchfähigkeit',
            'Fortschrittliche DPM (Direct Part Marking) Dekodierung',
            'Modbus, Ethernet/IP, PROFINET-Unterstützung',
            'USB-A & WLAN Auto-Forward Konnektivität',
          ],
          fr: [
            'Mise au point automatique rapide et précise en temps réel',
            'Résiste à plusieurs tests de chute de 1,8m',
            'IP67 — étanche à la poussière & immersion complète dans l\'eau',
            'Décodage DPM avancé (marquage direct de pièces)',
            'Support Modbus, Ethernet/IP, PROFINET',
            'Connectivité USB-A & WiFi Auto-Forward',
          ],
          it: [
            'Messa a fuoco automatica rapida e precisa in tempo reale',
            'Resiste a più test di caduta da 1,8m',
            'IP67 — a tenuta di polvere & immersione completa in acqua',
            'Decodifica DPM avanzata (marcatura diretta di parti)',
            'Supporto Modbus, Ethernet/IP, PROFINET',
            'Connettività USB-A & WiFi Auto-Forward',
          ],
          es: [
            'Autoenfoque rápido y preciso en tiempo real',
            'Resiste múltiples pruebas de caída de 1,8m',
            'IP67 — a prueba de polvo e inmersión completa en agua',
            'Decodificación DPM avanzada (marcado directo de piezas)',
            'Soporte Modbus, Ethernet/IP, PROFINET',
            'Conectividad USB-A y WiFi Auto-Forward',
          ],
        },
        specs: [
          { label: 'Image Sensor', value: 'CMOS' },
          { label: 'Interface', value: 'USB-A, WiFi (Auto Fwd.)' },
          { label: 'IP Rating', value: 'IP67' },
          { label: 'Drop Resistance', value: '1.8m multiple drops' },
          { label: 'Decoding', value: 'All 1D/2D + DPM' },
          { label: 'Protocol', value: 'Modbus, Ethernet/IP, PROFINET' },
        ],
        image: '/images/products/zx-1060.png',
        accentColor: '#1A1A2E',
      },
      {
        id: 'zx-3020',
        model: 'ZX-3020',
        name: {
          en: '2D Image Fixed Industrial Scanner',
          ko: '2D 이미지 고정형 산업용 스캐너',
          'zh-TW': '2D 影像固定式工業掃描器',
          de: '2D-Bild-Stationär-Industriescanner',
          fr: 'Scanner Industriel Fixe à Image 2D',
          it: 'Scanner Industriale Fisso a Immagine 2D',
          es: 'Escáner Industrial Fijo de Imagen 2D',
        },
        tagline: {
          en: 'AI vision. Adaptive focus. Zero dead angles.',
          ko: 'AI 비전. 적응형 포커스. 제로 데드 앵글.',
          'zh-TW': 'AI 視覺。自適應對焦。零死角。',
          de: 'KI-Vision. Adaptiver Fokus. Null tote Winkel.',
          fr: 'Vision IA. Mise au point adaptative. Zéro angle mort.',
          it: 'Visione AI. Messa a fuoco adattiva. Zero angoli morti.',
          es: 'Visión IA. Enfoque adaptativo. Cero ángulos muertos.',
        },
        description: {
          en: 'The ZX-3020 redefines fixed-mount scanning with AI-powered image processing, one-key smart light setup, and flexible 10–100cm working distance with zero dead zones. Four light sources with 8 configurable modes adapt to any barcode, DPM, or surface.',
          ko: 'ZX-3020은 AI 기반 이미지 처리, 원키 스마트 조명 설정, 그리고 제로 데드존의 10–100cm 유연한 작업 거리로 고정형 스캐닝을 재정의합니다. 8가지 구성 가능한 모드의 4가지 광원이 모든 바코드, DPM 또는 표면에 적응합니다.',
          'zh-TW': 'ZX-3020 憑藉 AI 影像處理、一鍵智慧光源設定和 10–100cm 零死角彈性工作距離，重新定義固定式掃描。4 組光源配備 8 種可配置模式，適應任何條碼、DPM 或表面。',
          de: 'Der ZX-3020 definiert stationäres Scannen neu mit KI-gestützter Bildverarbeitung, Ein-Tasten-Smart-Lichteinstellung und flexibler 10–100cm Arbeitsdistanz ohne tote Zonen. Vier Lichtquellen mit 8 konfigurierbaren Modi passen sich an jeden Barcode, DPM oder jede Oberfläche an.',
          fr: 'Le ZX-3020 redéfinit la numérisation en montage fixe avec un traitement d\'image alimenté par IA, une configuration d\'éclairage intelligent à une touche, et une distance de travail flexible de 10–100cm sans zones mortes. Quatre sources lumineuses avec 8 modes configurables s\'adaptent à tout code-barres, DPM ou surface.',
          it: 'Il ZX-3020 ridefinisce la scansione a montaggio fisso con elaborazione delle immagini basata su AI, configurazione dell\'illuminazione intelligente con un tasto e distanza di lavoro flessibile da 10–100cm senza zone morte. Quattro sorgenti luminose con 8 modalità configurabili si adattano a qualsiasi codice a barre, DPM o superficie.',
          es: 'El ZX-3020 redefine el escaneo en montaje fijo con procesamiento de imágenes impulsado por IA, configuración de iluminación inteligente de una tecla y distancia de trabajo flexible de 10–100cm sin zonas muertas. Cuatro fuentes de luz con 8 modos configurables se adaptan a cualquier código de barras, DPM o superficie.',
        },
        features: {
          en: [
            'AI image processing — instant color & code recognition',
            'Smart focus: adjustable lens, 100–1500mm DOF',
            'One-key light source configuration',
            '4 light sources × 8 modes for any surface',
            '10–100cm flexible working distance, zero dead angles',
            'RS232, Ethernet, Profibus, EtherNet/IP, PROFINET, EtherCAT',
            'CE, FCC, VCCI, BSMI, UKCA certified',
          ],
          ko: [
            'AI 이미지 처리 — 즉각적인 색상 및 코드 인식',
            '스마트 포커스: 조정 가능한 렌즈, 100–1500mm DOF',
            '원키 광원 구성',
            '모든 표면을 위한 4가지 광원 × 8가지 모드',
            '10–100cm 유연한 작업 거리, 제로 데드 앵글',
            'RS232, Ethernet, Profibus, EtherNet/IP, PROFINET, EtherCAT',
            'CE, FCC, VCCI, BSMI, UKCA 인증',
          ],
          'zh-TW': [
            'AI 影像處理 — 即時色彩和條碼識別',
            '智慧對焦：可調鏡頭，DOF 100–1500mm',
            '一鍵光源配置',
            '4 組光源 × 8 種模式，適應任何表面',
            '10–100cm 彈性工作距離，零死角',
            '支援 RS232、Ethernet、Profibus、EtherNet/IP、PROFINET、EtherCAT',
            'CE、FCC、VCCI、BSMI、UKCA 認證',
          ],
          de: [
            'KI-Bildverarbeitung — sofortige Farb- & Code-Erkennung',
            'Smart-Fokus: einstellbare Linse, 100–1500mm DOF',
            'Ein-Tasten-Lichtquellenkonfiguration',
            '4 Lichtquellen × 8 Modi für jede Oberfläche',
            '10–100cm flexible Arbeitsdistanz, null tote Winkel',
            'RS232, Ethernet, Profibus, EtherNet/IP, PROFINET, EtherCAT',
            'CE, FCC, VCCI, BSMI, UKCA zertifiziert',
          ],
          fr: [
            'Traitement d\'image IA — reconnaissance instantanée des couleurs et codes',
            'Mise au point intelligente : objectif réglable, DOF 100–1500mm',
            'Configuration de source lumineuse à une touche',
            '4 sources lumineuses × 8 modes pour toute surface',
            'Distance de travail flexible de 10–100cm, zéro angle mort',
            'RS232, Ethernet, Profibus, EtherNet/IP, PROFINET, EtherCAT',
            'Certifié CE, FCC, VCCI, BSMI, UKCA',
          ],
          it: [
            'Elaborazione immagini AI — riconoscimento istantaneo di colori e codici',
            'Messa a fuoco intelligente: obiettivo regolabile, DOF 100–1500mm',
            'Configurazione sorgente luminosa con un tasto',
            '4 sorgenti luminose × 8 modalità per qualsiasi superficie',
            'Distanza di lavoro flessibile 10–100cm, zero angoli morti',
            'RS232, Ethernet, Profibus, EtherNet/IP, PROFINET, EtherCAT',
            'Certificato CE, FCC, VCCI, BSMI, UKCA',
          ],
          es: [
            'Procesamiento de imágenes IA — reconocimiento instantáneo de colores y códigos',
            'Enfoque inteligente: lente ajustable, DOF 100–1500mm',
            'Configuración de fuente de luz con una tecla',
            '4 fuentes de luz × 8 modos para cualquier superficie',
            'Distancia de trabajo flexible de 10–100cm, cero ángulos muertos',
            'RS232, Ethernet, Profibus, EtherNet/IP, PROFINET, EtherCAT',
            'Certificado CE, FCC, VCCI, BSMI, UKCA',
          ],
        },
        specs: [
          { label: 'Image Sensor', value: '1280 × 800 CMOS' },
          { label: 'DOF', value: '100–1500mm (Adjustable Focus)' },
          { label: 'Dimension', value: '55 × 55.5 × 65 mm' },
          { label: 'Weight', value: '229 g' },
          { label: 'Power', value: '24 VDC / 15W' },
          { label: 'Interface', value: 'RS232, Ethernet, EtherCAT, PROFINET, Modbus TCP' },
          { label: 'IP Rating', value: 'IP65' },
          { label: 'Certification', value: 'CE, FCC, VCCI, BSMI, UKCA' },
        ],
        image: '/images/products/zx-3020.png',
        accentColor: '#D4192C',
      },
      {
        id: 'zx-3050',
        model: 'ZX-3050',
        name: {
          en: '2D Image Fixed Industrial Scanner',
          ko: '2D 이미지 고정형 산업용 스캐너',
          'zh-TW': '2D 影像固定式工業掃描器',
          de: '2D-Bild-Stationär-Industriescanner',
          fr: 'Scanner Industriel Fixe à Image 2D',
          it: 'Scanner Industriale Fisso a Immagine 2D',
          es: 'Escáner Industrial Fijo de Imagen 2D',
        },
        tagline: {
          en: 'Quad-core speed meets wide-field vision.',
          ko: '쿼드 코어 속도가 광각 비전을 만나다.',
          'zh-TW': '四核心速度結合寬視野視覺。',
          de: 'Quad-Core-Geschwindigkeit trifft Weitwinkel-Vision.',
          fr: 'Vitesse quad-core et vision grand angle.',
          it: 'Velocità quad-core e visione grandangolare.',
          es: 'Velocidad quad-core y visión de campo amplio.',
        },
        description: {
          en: 'The ZX-3050 combines a quad-linear high-speed processor with a high-resolution sensor, dual red and white lighting, and a wide field of view to deliver industrial-grade scanning at unmatched throughput. IP65-rated for water and dust protection.',
          ko: 'ZX-3050은 쿼드 리니어 고속 프로세서와 고해상도 센서, 이중 적색/백색 조명, 광각 시야를 결합하여 탁월한 처리량으로 산업용 스캐닝을 제공합니다. 방수 및 방진 IP65 등급.',
          'zh-TW': 'ZX-3050 結合四線性高速處理器和高解析度感測器、紅白雙光照明及寬視野，以無與倫比的吞吐量提供工業級掃描。IP65 等級，防水防塵。',
          de: 'Der ZX-3050 kombiniert einen Quad-linearen Hochgeschwindigkeitsprozessor mit einem hochauflösenden Sensor, dualer Rot-Weiß-Beleuchtung und Weitwinkel-Sichtfeld für industrielles Scannen mit unübertroffenem Durchsatz. IP65-zertifiziert.',
          fr: 'Le ZX-3050 combine un processeur quad-linéaire haute vitesse avec un capteur haute résolution, un éclairage rouge et blanc double, et un large champ de vision pour offrir une numérisation industrielle à un débit inégalé. Certifié IP65 pour la protection contre l\'eau et la poussière.',
          it: 'Il ZX-3050 combina un processore quad-lineare ad alta velocità con un sensore ad alta risoluzione, doppia illuminazione rosso e bianco e un ampio campo visivo per offrire una scansione industriale con throughput senza pari. Certificato IP65 per la protezione da acqua e polvere.',
          es: 'El ZX-3050 combina un procesador de alta velocidad quad-lineal con un sensor de alta resolución, iluminación doble rojo y blanco y un amplio campo de visión para ofrecer escaneo industrial con un rendimiento inigualable. Con certificación IP65 para protección contra agua y polvo.',
        },
        features: {
          en: [
            'Quad-linear high-speed processor',
            'High-resolution CMOS sensor',
            'Dual lighting: red + white illumination',
            'Wide FOV with large depth of field',
            'One-touch autofocus setup',
            'IP65 industrial-grade water & dust protection',
          ],
          ko: [
            '쿼드 리니어 고속 프로세서',
            '고해상도 CMOS 센서',
            '이중 조명: 적색 + 백색 조명',
            '대형 피사계 심도의 광각 FOV',
            '원터치 자동 포커스 설정',
            'IP65 산업용 방수 및 방진',
          ],
          'zh-TW': [
            '四線性高速處理器',
            '高解析度 CMOS 感測器',
            '雙光照明：紅光 + 白光',
            '大景深寬視野 FOV',
            '一鍵自動對焦設置',
            'IP65 工業級防水防塵',
          ],
          de: [
            'Quad-linearer Hochgeschwindigkeitsprozessor',
            'Hochauflösender CMOS-Sensor',
            'Doppelbeleuchtung: Rot + Weiß',
            'Weites Sichtfeld mit großer Schärfentiefe',
            'Ein-Touch-Autofokus-Einrichtung',
            'IP65 industrietauglicher Wasser- & Staubschutz',
          ],
          fr: [
            'Processeur haute vitesse quad-linéaire',
            'Capteur CMOS haute résolution',
            'Double éclairage : rouge + blanc',
            'Grand champ de vision avec grande profondeur de champ',
            'Configuration autofocus en un toucher',
            'Protection industrielle IP65 contre l\'eau & la poussière',
          ],
          it: [
            'Processore ad alta velocità quad-lineare',
            'Sensore CMOS ad alta risoluzione',
            'Doppia illuminazione: rosso + bianco',
            'Ampio campo visivo con grande profondità di campo',
            'Configurazione autofocus con un tocco',
            'Protezione industriale IP65 contro acqua e polvere',
          ],
          es: [
            'Procesador de alta velocidad quad-lineal',
            'Sensor CMOS de alta resolución',
            'Iluminación doble: rojo + blanco',
            'Amplio campo de visión con gran profundidad de campo',
            'Configuración de autoenfoque en un toque',
            'Protección industrial IP65 contra agua y polvo',
          ],
        },
        specs: [
          { label: 'Processor', value: 'Quad-linear High-Speed' },
          { label: 'Sensor', value: 'High-Resolution CMOS' },
          { label: 'Lighting', value: 'Dual Red + White' },
          { label: 'IP Rating', value: 'IP65' },
          { label: 'Interface', value: 'Ethernet' },
          { label: 'Focus', value: 'One-Touch Autofocus' },
        ],
        image: '/images/products/zx-3050.png',
        accentColor: '#1A1A2E',
      },
    ],
    applications: {
      en: [
        {
          title: 'Automotive Assembly Lines',
          description: 'Track VIN plates, part labels, and DPM codes stamped directly on engine blocks and chassis — even with oil, grease, or laser-etched surfaces.',
          icon: '🚗',
        },
        {
          title: 'Pharmaceutical Packaging',
          description: 'Verify 2D DataMatrix and QR codes on blister packs and vials at line speed. Ensure traceability compliance across every serialized item.',
          icon: '💊',
        },
        {
          title: 'E-Commerce Fulfillment Centers',
          description: 'Capture barcodes on packages moving at high speed across multiple conveyor lanes with zero-angle dead zones and adaptive focus.',
          icon: '📫',
        },
        {
          title: 'Electronics Manufacturing',
          description: 'Read micro DPM codes laser-etched or chemically marked on PCBs, chips, and connectors with advanced image processing.',
          icon: '⚡',
        },
      ],
      ko: [
        {
          title: '자동차 조립 라인',
          description: '오일, 그리스 또는 레이저 에칭 표면에서도 엔진 블록 및 섀시에 직접 각인된 VIN 플레이트, 부품 라벨 및 DPM 코드를 추적합니다.',
          icon: '🚗',
        },
        {
          title: '제약 포장',
          description: '라인 속도에서 블리스터 팩과 바이알의 2D 데이터 매트릭스 및 QR 코드를 확인합니다. 직렬화된 모든 항목에 걸쳐 추적 가능성 준수를 보장합니다.',
          icon: '💊',
        },
        {
          title: '전자상거래 이행 센터',
          description: '제로 앵글 데드존과 적응형 포커스로 여러 컨베이어 레인을 고속으로 이동하는 패키지의 바코드를 캡처합니다.',
          icon: '📫',
        },
        {
          title: '전자 제조',
          description: '고급 이미지 처리로 PCB, 칩 및 커넥터에 레이저 에칭 또는 화학적으로 마킹된 마이크로 DPM 코드를 읽습니다.',
          icon: '⚡',
        },
      ],
      'zh-TW': [
        {
          title: '汽車裝配線',
          description: '追蹤直接刻印在引擎缸體和底盤上的 VIN 銘牌、零件標籤和 DPM 代碼——即使在沾有油污、油脂或雷射蝕刻的表面也能讀取。',
          icon: '🚗',
        },
        {
          title: '藥品包裝',
          description: '以生產線速度驗證泡殼包裝和小瓶上的 2D DataMatrix 和 QR 碼。確保每個序列化項目的可追溯性合規。',
          icon: '💊',
        },
        {
          title: '電商履行中心',
          description: '以零死角和自適應對焦捕獲多條輸送帶上高速移動包裹的條碼。',
          icon: '📫',
        },
        {
          title: '電子製造',
          description: '以先進影像處理讀取 PCB、晶片和連接器上雷射蝕刻或化學標記的微型 DPM 代碼。',
          icon: '⚡',
        },
      ],
      de: [
        {
          title: 'Automobil-Montagelinien',
          description: 'VIN-Schilder, Teileaufkleber und DPM-Codes verfolgen, die direkt auf Motorblöcke und Chassis gestanzt sind — auch bei Öl, Fett oder lasergeätzten Oberflächen.',
          icon: '🚗',
        },
        {
          title: 'Pharmazeutische Verpackung',
          description: '2D-DataMatrix- und QR-Codes auf Blisterpackungen und Fläschchen mit Liniengeschwindigkeit verifizieren. Rückverfolgbarkeit für jedes serialisierte Element sicherstellen.',
          icon: '💊',
        },
        {
          title: 'E-Commerce-Fulfillment-Zentren',
          description: 'Barcodes auf Paketen erfassen, die mit hoher Geschwindigkeit über mehrere Förderbandspuren bewegt werden — mit null toten Winkeln und adaptivem Fokus.',
          icon: '📫',
        },
        {
          title: 'Elektronikmontage',
          description: 'Mikro-DPM-Codes auf PCBs, Chips und Steckverbindern lesen, die laser-geätzt oder chemisch markiert sind — mit fortschrittlicher Bildverarbeitung.',
          icon: '⚡',
        },
      ],
      fr: [
        { title: 'Lignes d\'Assemblage Automobile', description: 'Suivez les plaques VIN, les étiquettes de pièces et les codes DPM estampés directement sur les blocs moteur et les châssis — même avec des surfaces huileuses, graisseuses ou laser-gravées.', icon: '🚗' },
        { title: 'Emballage Pharmaceutique', description: 'Vérifiez les codes DataMatrix 2D et QR sur les blisters et les flacons à la vitesse de ligne. Garantissez la conformité de traçabilité pour chaque article sérialisé.', icon: '💊' },
        { title: 'Centres de Traitement E-Commerce', description: 'Capturez les codes-barres sur des colis se déplaçant à grande vitesse sur plusieurs lignes de convoyeurs avec zéro angle mort et mise au point adaptative.', icon: '📫' },
        { title: 'Fabrication Électronique', description: 'Lisez les micro codes DPM gravés au laser ou marqués chimiquement sur les PCB, puces et connecteurs avec un traitement d\'image avancé.', icon: '⚡' },
      ],
      it: [
        { title: 'Linee di Assemblaggio Automotive', description: 'Tracciate targhe VIN, etichette di parti e codici DPM stampati direttamente su blocchi motore e telai — anche con superfici oleose, sgrassate o incise al laser.', icon: '🚗' },
        { title: 'Confezionamento Farmaceutico', description: 'Verificate codici DataMatrix 2D e QR su blister e flaconi alla velocità della linea. Garantite la conformità alla tracciabilità per ogni articolo serializzato.', icon: '💊' },
        { title: 'Centri di Fulfillment E-Commerce', description: 'Catturate codici a barre su pacchi che si muovono ad alta velocità su più corsie di trasporto con zero angoli morti e messa a fuoco adattiva.', icon: '📫' },
        { title: 'Produzione Elettronica', description: 'Leggete micro codici DPM incisi al laser o marcati chimicamente su PCB, chip e connettori con elaborazione avanzata delle immagini.', icon: '⚡' },
      ],
      es: [
        { title: 'Líneas de Ensamblaje Automotriz', description: 'Rastree placas VIN, etiquetas de piezas y códigos DPM estampados directamente en bloques de motor y chasis — incluso con superficies aceitosas, grasosas o grabadas con láser.', icon: '🚗' },
        { title: 'Envasado Farmacéutico', description: 'Verifique códigos DataMatrix 2D y QR en blisters y frascos a la velocidad de línea. Garantice el cumplimiento de trazabilidad en cada artículo serializado.', icon: '💊' },
        { title: 'Centros de Distribución de E-Commerce', description: 'Capture códigos de barras en paquetes que se mueven a alta velocidad por múltiples carriles de cinta transportadora con cero ángulos muertos y enfoque adaptativo.', icon: '📫' },
        { title: 'Fabricación Electrónica', description: 'Lea micro códigos DPM grabados con láser o marcados químicamente en PCB, chips y conectores con procesamiento de imagen avanzado.', icon: '⚡' },
      ],
    },
  },

  {
    id: 'scan-modules',
    name: {
      en: 'Scan Modules',
      ko: '스캔 모듈',
      'zh-TW': '掃描模組',
      de: 'Scan-Module',
      fr: 'Modules de Scan',
      it: 'Moduli di Scansione',
      es: 'Módulos de Escaneo',
    },
    tagline: {
      en: 'Embed scanning intelligence anywhere.',
      ko: '어디서나 스캔 인텔리전스를 내장.',
      'zh-TW': '隨處嵌入掃描智慧。',
      de: 'Scan-Intelligenz überall einbetten.',
      fr: 'Intégrez l\'intelligence de numérisation partout.',
      it: 'Integra l\'intelligenza di scansione ovunque.',
      es: 'Integra inteligencia de escaneo en cualquier lugar.',
    },
    heroImage: '/images/products/product-lineup.png',
    products: [
      {
        id: 'z-5552-plus',
        model: 'Z-5552 Plus',
        name: {
          en: '2D Image Scan Module',
          ko: '2D 이미지 스캔 모듈',
          'zh-TW': '2D 影像掃描模組',
          de: '2D-Bild-Scan-Modul',
          fr: 'Module de Scan à Image 2D',
          it: 'Modulo di Scansione a Immagine 2D',
          es: 'Módulo de Escaneo de Imagen 2D',
        },
        tagline: {
          en: 'The brain behind your kiosk or self-checkout.',
          ko: '키오스크 또는 셀프체크아웃의 두뇌.',
          'zh-TW': '您的自助服務機或自助結帳背後的大腦。',
          de: 'Das Gehirn hinter Ihrem Kiosk oder Self-Checkout.',
          fr: 'Le cerveau de votre kiosque ou self-checkout.',
          it: 'Il cervello del tuo chiosco o self-checkout.',
          es: 'El cerebro de tu quiosco o autoservicio.',
        },
        description: {
          en: 'Z-5552 Plus is a high-performance scan engine designed for embedding into kiosks, ATMs, vending machines, POS terminals, and self-checkout systems. Exceptional motion tolerance and screen-barcode reading capability make it ideal for modern omnichannel retail and smart hospitality.',
          ko: 'Z-5552 Plus는 키오스크, ATM, 자판기, POS 단말기 및 셀프 체크아웃 시스템에 내장하기 위해 설계된 고성능 스캔 엔진입니다. 탁월한 모션 내성과 화면 바코드 읽기 기능으로 현대적인 옴니채널 소매 및 스마트 호스피탈리티에 이상적입니다.',
          'zh-TW': 'Z-5552 Plus 是一款高效能掃描引擎，專為嵌入自助服務機、ATM、自動販賣機、POS 終端機和自助結帳系統而設計。卓越的動態容錯能力和螢幕條碼讀取功能，使其成為現代全通路零售和智慧款待業的理想選擇。',
          de: 'Z-5552 Plus ist ein leistungsstarkes Scan-Engine für den Einbau in Kioske, Geldautomaten, Verkaufsautomaten, POS-Terminals und Self-Checkout-Systeme. Außergewöhnliche Bewegungstoleranz und Bildschirm-Barcode-Lesefähigkeit machen es ideal für modernen Omnichannel-Einzelhandel.',
          fr: 'Le Z-5552 Plus est un moteur de scan haute performance conçu pour être intégré dans des kiosques, distributeurs automatiques, terminaux POS et systèmes self-checkout. Sa tolérance exceptionnelle aux mouvements et sa capacité à lire les codes-barres sur écran le rendent idéal pour le commerce omnicanal moderne et l\'hôtellerie intelligente.',
          it: 'Z-5552 Plus è un motore di scansione ad alte prestazioni progettato per essere integrato in chioschi, bancomat, distributori automatici, terminali POS e sistemi self-checkout. L\'eccezionale tolleranza al movimento e la capacità di lettura dei codici a barre su schermo lo rendono ideale per il retail omnicanale moderno e l\'ospitalità intelligente.',
          es: 'El Z-5552 Plus es un motor de escaneo de alto rendimiento diseñado para integrarse en quioscos, cajeros automáticos, máquinas expendedoras, terminales POS y sistemas de autoservicio. Su excepcional tolerancia al movimiento y capacidad de lectura de códigos de barras en pantalla lo hacen ideal para el comercio minorista omnicanal moderno.',
        },
        features: {
          en: [
            'Exceptional motion tolerance for moving targets',
            'Reads 1D & 2D codes from screens (phone, tablet, monitor)',
            'Captures barcodes off any display surface',
            'Designed for kiosk, ATM & POS integration',
            'Wide-angle 1280 × 800 CMOS sensor',
            'Flexible DOF: 40–440mm (Code 39 3mil)',
          ],
          ko: [
            '이동 목표를 위한 탁월한 모션 내성',
            '화면(휴대폰, 태블릿, 모니터)에서 1D 및 2D 코드 읽기',
            '모든 디스플레이 표면에서 바코드 캡처',
            '키오스크, ATM 및 POS 통합을 위해 설계',
            '광각 1280 × 800 CMOS 센서',
            '유연한 DOF: 40–440mm (Code 39 3mil)',
          ],
          'zh-TW': [
            '卓越的動態容錯能力，適用於移動目標',
            '讀取螢幕（手機、平板、監視器）上的 1D 和 2D 條碼',
            '捕獲任何顯示表面的條碼',
            '專為自助服務機、ATM 和 POS 整合設計',
            '廣角 1280 × 800 CMOS 感測器',
            '彈性 DOF：40–440mm（Code 39 3mil）',
          ],
          de: [
            'Außergewöhnliche Bewegungstoleranz für bewegliche Ziele',
            'Liest 1D & 2D Codes von Bildschirmen (Handy, Tablet, Monitor)',
            'Erfasst Barcodes von jeder Displayoberfläche',
            'Konzipiert für Kiosk-, ATM- & POS-Integration',
            'Weitwinkel 1280 × 800 CMOS-Sensor',
            'Flexibler DOF: 40–440mm (Code 39 3mil)',
          ],
          fr: [
            'Tolérance de mouvement exceptionnelle pour les cibles mobiles',
            'Lit les codes 1D & 2D sur les écrans (téléphone, tablette, moniteur)',
            'Capture les codes-barres sur toute surface d\'affichage',
            'Conçu pour l\'intégration kiosque, ATM & POS',
            'Capteur CMOS grand angle 1280 × 800',
            'DOF flexible : 40–440mm (Code 39 3mil)',
          ],
          it: [
            'Tolleranza al movimento eccezionale per bersagli in movimento',
            'Legge codici 1D & 2D da schermi (telefono, tablet, monitor)',
            'Cattura codici a barre da qualsiasi superficie display',
            'Progettato per l\'integrazione in chioschi, bancomat & POS',
            'Sensore CMOS grandangolare 1280 × 800',
            'DOF flessibile: 40–440mm (Code 39 3mil)',
          ],
          es: [
            'Tolerancia al movimiento excepcional para objetivos en movimiento',
            'Lee códigos 1D y 2D de pantallas (teléfono, tableta, monitor)',
            'Captura códigos de barras de cualquier superficie de pantalla',
            'Diseñado para integración en quioscos, cajeros automáticos y POS',
            'Sensor CMOS gran angular 1280 × 800',
            'DOF flexible: 40–440mm (Code 39 3mil)',
          ],
        },
        specs: [
          { label: 'Image Sensor', value: '1280 × 800 CMOS' },
          { label: 'DOF (Code 39 3mil)', value: '40–440 mm' },
          { label: 'DOF (EAN-13)', value: '80–110 mm' },
          { label: 'DOF (Code 128 8mil)', value: '40–110 mm' },
          { label: 'DOF (Code 128 6mil)', value: '40–220 mm' },
          { label: 'Min. Resolution', value: '3 mil (30:)' },
          { label: 'Screen Reading', value: 'Mobile, Tablet, Monitor' },
        ],
        image: '/images/products/z-5552-plus.png',
        accentColor: '#D4192C',
      },
    ],
    applications: {
      en: [
        {
          title: 'Self-Checkout & Retail POS',
          description: 'Deliver fast, reliable scanning in self-checkout kiosks and retail POS terminals — reads both printed labels and mobile wallet barcodes from any angle.',
          icon: '🏪',
        },
        {
          title: 'Smart Vending & ATM',
          description: 'Enable contactless QR code redemption in vending machines and ATMs, capturing codes from cracked, worn, or screen-displayed sources.',
          icon: '🏧',
        },
        {
          title: 'Healthcare & Patient ID Kiosks',
          description: 'Read patient wristband barcodes, insurance cards, and e-prescriptions reliably in clinical environments with high hygiene demands.',
          icon: '🏥',
        },
        {
          title: 'Event & Ticketing Gates',
          description: 'Process mobile tickets, QR passes, and NFC codes at access control points with zero-miss scanning under varied lighting conditions.',
          icon: '🎫',
        },
      ],
      ko: [
        {
          title: '셀프 체크아웃 및 소매 POS',
          description: '셀프 체크아웃 키오스크와 소매 POS 단말기에서 빠르고 신뢰할 수 있는 스캐닝을 제공합니다 — 어떤 각도에서도 인쇄 라벨과 모바일 지갑 바코드를 모두 읽습니다.',
          icon: '🏪',
        },
        {
          title: '스마트 자판기 및 ATM',
          description: '자판기와 ATM에서 비접촉 QR 코드 사용을 가능하게 하며, 긁힌, 마모된 또는 화면 표시된 소스에서 코드를 캡처합니다.',
          icon: '🏧',
        },
        {
          title: '의료 및 환자 ID 키오스크',
          description: '위생 요구가 높은 임상 환경에서 환자 팔찌 바코드, 보험 카드 및 전자 처방전을 안정적으로 읽습니다.',
          icon: '🏥',
        },
        {
          title: '이벤트 및 티켓팅 게이트',
          description: '다양한 조명 조건에서 제로 미스 스캐닝으로 액세스 제어 지점에서 모바일 티켓, QR 패스 및 NFC 코드를 처리합니다.',
          icon: '🎫',
        },
      ],
      'zh-TW': [
        {
          title: '自助結帳和零售 POS',
          description: '在自助結帳自助服務機和零售 POS 終端機中提供快速可靠的掃描——從任意角度讀取印刷標籤和行動錢包條碼。',
          icon: '🏪',
        },
        {
          title: '智慧自動販賣機和 ATM',
          description: '在自動販賣機和 ATM 中實現非接觸式 QR 碼兌換，捕獲破損、磨損或螢幕顯示來源的條碼。',
          icon: '🏧',
        },
        {
          title: '醫療和患者 ID 自助服務機',
          description: '在衛生要求高的臨床環境中可靠地讀取患者手環條碼、保險卡和電子處方。',
          icon: '🏥',
        },
        {
          title: '活動和票務閘門',
          description: '在不同照明條件下，以零遺漏掃描在門禁控制點處理行動票券、QR 通行證和 NFC 碼。',
          icon: '🎫',
        },
      ],
      de: [
        {
          title: 'Self-Checkout & Einzelhandels-POS',
          description: 'Schnelles, zuverlässiges Scannen in Self-Checkout-Kiosken und Einzelhandels-POS-Terminals — liest gedruckte Etiketten und Mobile-Wallet-Barcodes aus jedem Winkel.',
          icon: '🏪',
        },
        {
          title: 'Smart-Automaten & Geldautomaten',
          description: 'Kontaktlose QR-Code-Einlösung in Verkaufsautomaten und Geldautomaten — erfasst Codes von beschädigten, abgenutzten oder bildschirmangezeigten Quellen.',
          icon: '🏧',
        },
        {
          title: 'Gesundheitswesen & Patienten-ID-Kioske',
          description: 'Patientenarmband-Barcodes, Versicherungskarten und E-Rezepte in klinischen Umgebungen mit hohen Hygieneanforderungen zuverlässig lesen.',
          icon: '🏥',
        },
        {
          title: 'Veranstaltungs- & Ticketing-Gates',
          description: 'Mobile Tickets, QR-Pässe und NFC-Codes an Zugangskontrollpunkten unter wechselnden Lichtverhältnissen mit null Fehllesungen verarbeiten.',
          icon: '🎫',
        },
      ],
      fr: [
        { title: 'Self-Checkout & POS de Vente au Détail', description: 'Offrez une numérisation rapide et fiable dans les kiosques self-checkout et les terminaux POS — lit les étiquettes imprimées et les codes-barres de portefeuille mobile depuis n\'importe quel angle.', icon: '🏪' },
        { title: 'Distributeurs Intelligents & DAB', description: 'Activez l\'échange de QR codes sans contact dans les distributeurs et DAB, en capturant les codes depuis des sources endommagées, usées ou affichées à l\'écran.', icon: '🏧' },
        { title: 'Kiosques Santé & Identification Patient', description: 'Lisez de manière fiable les codes-barres des bracelets patients, les cartes d\'assurance et les ordonnances électroniques dans des environnements cliniques à haute exigence hygiénique.', icon: '🏥' },
        { title: 'Portiques d\'Événements & Billetterie', description: 'Traitez les billets mobiles, passes QR et codes NFC aux points de contrôle d\'accès avec zéro raté sous des conditions d\'éclairage variées.', icon: '🎫' },
      ],
      it: [
        { title: 'Self-Checkout & POS al Dettaglio', description: 'Offrite una scansione rapida e affidabile nei chioschi self-checkout e nei terminali POS al dettaglio — legge etichette stampate e codici a barre da portafoglio mobile da qualsiasi angolo.', icon: '🏪' },
        { title: 'Distributori Intelligenti & Bancomat', description: 'Abilitate il riscatto di QR code contactless in distributori automatici e bancomat, catturando codici da fonti danneggiate, consumate o visualizzate su schermo.', icon: '🏧' },
        { title: 'Chioschi Sanitari & ID Paziente', description: 'Leggete in modo affidabile codici a barre dei braccialetti pazienti, carte assicurative ed e-prescrizioni in ambienti clinici ad alta richiesta igienica.', icon: '🏥' },
        { title: 'Portali per Eventi & Biglietteria', description: 'Elaborate biglietti mobili, pass QR e codici NFC ai punti di controllo accessi con zero mancate letture sotto condizioni di illuminazione variabili.', icon: '🎫' },
      ],
      es: [
        { title: 'Self-Checkout y POS Minorista', description: 'Ofrezca escaneo rápido y fiable en quioscos de autoservicio y terminales POS minoristas — lee etiquetas impresas y códigos de barras de monedero móvil desde cualquier ángulo.', icon: '🏪' },
        { title: 'Máquinas Expendedoras Inteligentes y Cajeros Automáticos', description: 'Habilite el canje de códigos QR sin contacto en máquinas expendedoras y cajeros automáticos, capturando códigos de fuentes dañadas, desgastadas o mostradas en pantalla.', icon: '🏧' },
        { title: 'Quioscos de Salud e Identificación de Pacientes', description: 'Lea de forma fiable códigos de barras de pulseras de pacientes, tarjetas de seguro y recetas electrónicas en entornos clínicos con altas exigencias higiénicas.', icon: '🏥' },
        { title: 'Puertas de Eventos y Boletería', description: 'Procese entradas móviles, pases QR y códigos NFC en puntos de control de acceso con cero errores de lectura bajo condiciones de iluminación variadas.', icon: '🎫' },
      ],
    },
  },

  {
    id: 'handheld-scanners',
    name: {
      en: 'Handheld Scanners',
      ko: '핸드헬드 스캐너',
      'zh-TW': '手持式掃描器',
      de: 'Handscanner',
      fr: 'Scanners Portables',
      it: 'Scanner Portatili',
      es: 'Escáneres de Mano',
    },
    tagline: {
      en: 'Built rugged. Reads everything.',
      ko: '견고하게 제작. 모든 것을 읽다.',
      'zh-TW': '堅固耐用。讀取一切。',
      de: 'Robust gebaut. Liest alles.',
      fr: 'Robuste. Lit tout.',
      it: 'Costruito robusto. Legge tutto.',
      es: 'Construido robusto. Lee todo.',
    },
    heroImage: '/images/products/handheld-lineup.png',
    products: [
      {
        id: 'z-3572',
        model: 'Z-3572',
        name: {
          en: '2D Image Handheld Scanner (Full Range)',
          ko: '2D 이미지 핸드헬드 스캐너 (풀레인지)',
          'zh-TW': '2D 影像手持掃描器（全距離）',
          de: '2D-Bild-Handscanner (Vollbereich)',
          fr: 'Scanner Portable à Image 2D (Pleine Portée)',
          it: 'Scanner Portatile a Immagine 2D (Portata Completa)',
          es: 'Escáner de Mano de Imagen 2D (Alcance Completo)',
        },
        tagline: {
          en: 'Dual-lens. From 14cm to 3 meters.',
          ko: '듀얼 렌즈. 14cm에서 3미터까지.',
          'zh-TW': '雙鏡頭。從 14cm 到 3 公尺。',
          de: 'Dual-Linse. Von 14cm bis 3 Meter.',
          fr: 'Double objectif. De 14cm à 3 mètres.',
          it: 'Doppio obiettivo. Da 14cm a 3 metri.',
          es: 'Doble lente. De 14cm a 3 metros.',
        },
        description: {
          en: 'The Z-3572 features a unique dual-CMOS lens system giving it full-range reading capability from close-up 14cm detail work to warehouse-spanning 3-meter distance reads. IP54-rated rugged housing survives drops, dust, and demanding environments.',
          ko: 'Z-3572는 독특한 듀얼 CMOS 렌즈 시스템으로 근접 14cm 세부 작업에서 창고를 가로지르는 3미터 거리 읽기까지 전 범위 읽기 기능을 제공합니다. IP54 등급 견고한 하우징으로 낙하, 먼지, 까다로운 환경을 견딥니다.',
          'zh-TW': 'Z-3572 具備獨特的雙 CMOS 鏡頭系統，提供全距離讀取能力，從近距離 14cm 細節工作到橫跨倉庫 3 公尺距離讀取。IP54 等級堅固外殼可承受跌落、灰塵和惡劣環境。',
          de: 'Der Z-3572 verfügt über ein einzigartiges Dual-CMOS-Linsensystem, das Vollbereichs-Lesefähigkeit von 14cm Nahaufnahme-Detailarbeit bis zu 3-Meter-Fernlesen im Lager bietet. IP54-zertifiziertes robustes Gehäuse übersteht Stürze, Staub und anspruchsvolle Umgebungen.',
          fr: 'Le Z-3572 dispose d\'un système unique à double objectif CMOS offrant une capacité de lecture pleine portée, du travail de détail en gros plan à 14cm aux lectures à 3 mètres pour les entrepôts. Le boîtier robuste classé IP54 résiste aux chutes, à la poussière et aux environnements exigeants.',
          it: 'Il Z-3572 dispone di un sistema unico a doppio obiettivo CMOS che offre capacità di lettura a portata completa, dal lavoro di dettaglio ravvicinato a 14cm alle letture a distanza di 3 metri in magazzino. La robusta custodia certificata IP54 resiste a cadute, polvere e ambienti impegnativi.',
          es: 'El Z-3572 dispone de un sistema único de doble lente CMOS que le otorga capacidad de lectura de alcance completo, desde el trabajo de detalle a 14cm hasta lecturas a 3 metros en almacenes. El robusto housing con certificación IP54 resiste caídas, polvo y entornos exigentes.',
        },
        features: {
          en: [
            'Dual-CMOS lens: close-range + long-range in one device',
            'Full reading range: 14cm to 300cm (Code 128)',
            'Extended DOF for versatile workspaces',
            'IP54 — dust & splash resistant',
            'Rugged housing for peak performance anywhere',
            'Decodes all standard 1D & 2D symbologies',
          ],
          ko: [
            '듀얼 CMOS 렌즈: 하나의 장치에 근거리 + 장거리',
            '전체 읽기 범위: 14cm ~ 300cm (Code 128)',
            '다재다능한 작업 공간을 위한 확장된 DOF',
            'IP54 — 방진 및 방수 스플래시',
            '어디서나 최고의 성능을 위한 견고한 하우징',
            '모든 표준 1D 및 2D 심볼로지 디코딩',
          ],
          'zh-TW': [
            '雙 CMOS 鏡頭：一台設備兼顧近距離 + 遠距離',
            '全讀取範圍：14cm 至 300cm（Code 128）',
            '延伸 DOF，適用於多種工作場所',
            'IP54 — 防塵且防濺水',
            '堅固外殼，隨處表現卓越',
            '解碼所有標準 1D 和 2D 符號系統',
          ],
          de: [
            'Dual-CMOS-Linse: Nah- + Weitbereich in einem Gerät',
            'Vollständiger Lesebereich: 14cm bis 300cm (Code 128)',
            'Erweiterter DOF für vielseitige Arbeitsbereiche',
            'IP54 — staub- & spritzwasserbeständig',
            'Robustes Gehäuse für Höchstleistung überall',
            'Dekodiert alle Standard-1D- & 2D-Symbologien',
          ],
          fr: [
            'Double objectif CMOS : courte portée + longue portée en un seul appareil',
            'Plage de lecture complète : 14cm à 300cm (Code 128)',
            'DOF étendu pour des espaces de travail polyvalents',
            'IP54 — résistant à la poussière & aux éclaboussures',
            'Boîtier robuste pour des performances maximales partout',
            'Décode toutes les symbologies 1D & 2D standard',
          ],
          it: [
            'Doppio obiettivo CMOS: corto raggio + lungo raggio in un solo dispositivo',
            'Portata di lettura completa: 14cm a 300cm (Code 128)',
            'DOF esteso per spazi di lavoro versatili',
            'IP54 — resistente a polvere & spruzzi',
            'Custodia robusta per prestazioni ottimali ovunque',
            'Decodifica tutte le simbologie 1D & 2D standard',
          ],
          es: [
            'Doble lente CMOS: corto alcance + largo alcance en un solo dispositivo',
            'Rango de lectura completo: 14cm a 300cm (Code 128)',
            'DOF extendido para espacios de trabajo versátiles',
            'IP54 — resistente al polvo y salpicaduras',
            'Housing robusto para máximo rendimiento en cualquier lugar',
            'Decodifica todas las simbologías 1D y 2D estándar',
          ],
        },
        specs: [
          { label: 'Image Sensor', value: '1280 × 1080 Dual-CMOS' },
          { label: 'DOF (Code 39 3mil)', value: '140–400 mm' },
          { label: 'DOF (Code 128 8mil)', value: '120–1,000 mm' },
          { label: 'DOF (Code 128 6mil)', value: '40–3,000 mm' },
          { label: 'Min. Resolution', value: '10 mil (20:)' },
          { label: 'IP Rating', value: 'IP54' },
        ],
        image: '/images/products/z-3572.png',
        accentColor: '#D4192C',
      },
      {
        id: 'z-3502',
        model: 'Z-3502',
        name: {
          en: '2D Image Handheld Scanner',
          ko: '2D 이미지 핸드헬드 스캐너',
          'zh-TW': '2D 影像手持掃描器',
          de: '2D-Bild-Handscanner',
          fr: 'Scanner Portable à Image 2D',
          it: 'Scanner Portatile a Immagine 2D',
          es: 'Escáner de Mano de Imagen 2D',
        },
        tagline: {
          en: 'Drop-proof. Waterproof. DPM-ready.',
          ko: '낙하 방지. 방수. DPM 준비.',
          'zh-TW': '防摔。防水。支援 DPM。',
          de: 'Sturzsicher. Wasserdicht. DPM-bereit.',
          fr: 'Résistant aux chutes. Étanche. Prêt pour DPM.',
          it: 'Resistente alle cadute. Impermeabile. Pronto per DPM.',
          es: 'Resistente a caídas. Impermeable. Listo para DPM.',
        },
        description: {
          en: 'The Z-3502 is engineered for the toughest handheld environments. IP54-rated and verified to survive 1.8m drops to concrete. Flexible lighting adapts to any reflective or non-reflective surface, while advanced DPM decoding handles direct part marks in automotive, aerospace, and electronics.',
          ko: 'Z-3502는 가장 까다로운 핸드헬드 환경을 위해 설계되었습니다. IP54 등급이며 콘크리트에 1.8m 낙하를 견디는 것이 검증되었습니다. 유연한 조명이 반사 또는 비반사 표면에 적응하며, 고급 DPM 디코딩은 자동차, 항공우주 및 전자 산업의 직접 부품 마크를 처리합니다.',
          'zh-TW': 'Z-3502 專為最嚴苛的手持環境而設計。IP54 等級，經驗證可承受 1.8m 跌落至混凝土地面。彈性照明適應任何反射或非反射表面，同時先進的 DPM 解碼處理汽車、航太和電子行業的直接零件標記。',
          de: 'Der Z-3502 ist für die härtesten Handscanner-Umgebungen konzipiert. IP54-zertifiziert und validiert für 1,8m-Stürze auf Beton. Flexible Beleuchtung passt sich reflektierenden und nicht reflektierenden Oberflächen an, während die DPM-Dekodierung direkte Teilemarkierungen in Automobil-, Luft- und Elektronikbereichen verarbeitet.',
          fr: 'Le Z-3502 est conçu pour les environnements portables les plus difficiles. Classé IP54 et vérifié pour résister à des chutes de 1,8m sur béton. L\'éclairage flexible s\'adapte à toute surface réfléchissante ou non réfléchissante, tandis que le décodage DPM avancé gère les marquages directs de pièces dans l\'automobile, l\'aérospatiale et l\'électronique.',
          it: 'Il Z-3502 è progettato per gli ambienti portatili più difficili. Certificato IP54 e verificato per resistere a cadute di 1,8m sul cemento. L\'illuminazione flessibile si adatta a qualsiasi superficie riflettente o non riflettente, mentre la decodifica DPM avanzata gestisce le marcature dirette di parti in ambito automotive, aerospaziale ed elettronico.',
          es: 'El Z-3502 está diseñado para los entornos de escáner de mano más exigentes. Con certificación IP54 y verificado para resistir caídas de 1,8m sobre hormigón. La iluminación flexible se adapta a cualquier superficie reflectante o no reflectante, mientras que la decodificación DPM avanzada gestiona las marcas directas de piezas en automoción, aeroespacial y electrónica.',
        },
        features: {
          en: [
            'IP54: dust-tight & water-jet protected',
            'Survives 1.8m drops to concrete — multiple times',
            'Flexible lighting for reflective & non-reflective surfaces',
            'Advanced DPM decoding for stamped/etched marks',
            '1280 × 1080 CMOS high-res sensor',
            'Reading range up to 1,000mm (Code GR 13mil)',
          ],
          ko: [
            'IP54: 방진 및 수류 보호',
            '콘크리트에 1.8m 낙하를 여러 번 견딤',
            '반사 및 비반사 표면을 위한 유연한 조명',
            '각인/에칭 마크를 위한 고급 DPM 디코딩',
            '1280 × 1080 CMOS 고해상도 센서',
            '최대 1,000mm 읽기 범위 (Code GR 13mil)',
          ],
          'zh-TW': [
            'IP54：防塵且耐水柱噴射保護',
            '可多次承受 1.8m 跌落至混凝土地面',
            '彈性照明，適應反射和非反射表面',
            '先進的 DPM 解碼，適用於刻印/蝕刻標記',
            '1280 × 1080 CMOS 高解析度感測器',
            '讀取範圍達 1,000mm（Code GR 13mil）',
          ],
          de: [
            'IP54: staubdicht & wasserstrahlgeschützt',
            'Übersteht 1,8m-Stürze auf Beton — mehrfach',
            'Flexible Beleuchtung für reflektierende & nicht reflektierende Oberflächen',
            'Erweiterte DPM-Dekodierung für gestanzte/geätzte Markierungen',
            '1280 × 1080 CMOS hochauflösender Sensor',
            'Lesebereich bis zu 1.000mm (Code GR 13mil)',
          ],
          fr: [
            'IP54 : étanche à la poussière & protégé contre les jets d\'eau',
            'Résiste à des chutes de 1,8m sur béton — plusieurs fois',
            'Éclairage flexible pour surfaces réfléchissantes & non réfléchissantes',
            'Décodage DPM avancé pour les marquages estampés/gravés',
            'Capteur CMOS haute résolution 1280 × 1080',
            'Portée de lecture jusqu\'à 1 000mm (Code GR 13mil)',
          ],
          it: [
            'IP54: a tenuta di polvere & protetto dai getti d\'acqua',
            'Resiste a cadute di 1,8m sul cemento — più volte',
            'Illuminazione flessibile per superfici riflettenti & non riflettenti',
            'Decodifica DPM avanzata per marcature stampate/incise',
            'Sensore CMOS ad alta risoluzione 1280 × 1080',
            'Portata di lettura fino a 1.000mm (Code GR 13mil)',
          ],
          es: [
            'IP54: a prueba de polvo y protegido contra chorros de agua',
            'Resiste caídas de 1,8m sobre hormigón — múltiples veces',
            'Iluminación flexible para superficies reflectantes y no reflectantes',
            'Decodificación DPM avanzada para marcas estampadas/grabadas',
            'Sensor CMOS de alta resolución 1280 × 1080',
            'Alcance de lectura hasta 1.000mm (Code GR 13mil)',
          ],
        },
        specs: [
          { label: 'Image Sensor', value: '1280 × 1080 CMOS' },
          { label: 'DOF (GR 3mil)', value: '40–100 mm' },
          { label: 'DOF (GR 13mil)', value: '40–1,000 mm' },
          { label: 'Min. Resolution', value: '5 mil (30:)' },
          { label: 'IP Rating', value: 'IP54' },
          { label: 'Drop Resistance', value: '1.8m multiple drops' },
        ],
        image: '/images/products/z-3502.png',
        accentColor: '#1A1A2E',
      },
    ],
    applications: {
      en: [
        {
          title: 'Warehouse & Logistics',
          description: 'Scan labels at ground level or overhead racking with the Z-3572 dual-lens system, eliminating the need for multiple scanners in one facility.',
          icon: '🏭',
        },
        {
          title: 'Field Service & Maintenance',
          description: 'Read DPM codes on machinery, pipes, and components in tight spaces or harsh outdoor conditions with Z-3502\'s IP54 rugged housing.',
          icon: '🔧',
        },
        {
          title: 'Aerospace & Defense MRO',
          description: 'Track serialized aircraft parts with laser-etched DPM codes that Z-3502 decodes reliably — even on curved, anodized, or low-contrast surfaces.',
          icon: '✈️',
        },
        {
          title: 'Retail & Inventory Management',
          description: 'Speed up cycle counts and receiving workflows in retail backrooms and distribution centers with high-motion-tolerance scanning.',
          icon: '🏬',
        },
      ],
      ko: [
        {
          title: '창고 및 물류',
          description: 'Z-3572 듀얼 렌즈 시스템으로 지상 레벨 또는 머리 위 랙에서 라벨을 스캔하여 한 시설에서 여러 스캐너의 필요성을 제거합니다.',
          icon: '🏭',
        },
        {
          title: '현장 서비스 및 유지 보수',
          description: 'Z-3502의 IP54 견고한 하우징으로 좁은 공간이나 가혹한 야외 조건의 기계, 파이프 및 부품의 DPM 코드를 읽습니다.',
          icon: '🔧',
        },
        {
          title: '항공우주 및 방위 MRO',
          description: 'Z-3502가 곡면, 양극 처리된 또는 낮은 대비 표면에서도 안정적으로 디코딩하는 레이저 에칭 DPM 코드로 직렬화된 항공기 부품을 추적합니다.',
          icon: '✈️',
        },
        {
          title: '소매 및 재고 관리',
          description: '높은 모션 내성 스캐닝으로 소매 후방 창고 및 유통 센터에서 재고 조사 및 수령 워크플로우를 가속화합니다.',
          icon: '🏬',
        },
      ],
      'zh-TW': [
        {
          title: '倉儲和物流',
          description: '使用 Z-3572 雙鏡頭系統掃描地面或頭頂貨架標籤，消除一個設施中需要多台掃描器的需求。',
          icon: '🏭',
        },
        {
          title: '現場服務和維護',
          description: '使用 Z-3502 的 IP54 堅固外殼，在狹小空間或惡劣戶外條件下讀取機械、管道和元件上的 DPM 代碼。',
          icon: '🔧',
        },
        {
          title: '航太和國防 MRO',
          description: '追蹤帶有雷射蝕刻 DPM 代碼的序列化飛機零件，Z-3502 可在彎曲、陽極氧化或低對比表面上可靠解碼。',
          icon: '✈️',
        },
        {
          title: '零售和庫存管理',
          description: '以高動態容錯掃描加速零售後室和配送中心的盤點和收貨工作流程。',
          icon: '🏬',
        },
      ],
      de: [
        {
          title: 'Lager & Logistik',
          description: 'Etiketten auf Bodenniveau oder Hochregallagen mit dem Z-3572 Dual-Linsen-System scannen — kein zweiter Scanner mehr nötig.',
          icon: '🏭',
        },
        {
          title: 'Außendienst & Wartung',
          description: 'DPM-Codes auf Maschinen, Rohren und Bauteilen in engen Räumen oder rauen Außenbedingungen mit dem IP54-robusten Z-3502 lesen.',
          icon: '🔧',
        },
        {
          title: 'Luft- & Raumfahrt / Verteidigung MRO',
          description: 'Serialisierte Flugzeugteile mit lasergeätzten DPM-Codes verfolgen — der Z-3502 dekodiert zuverlässig auf gebogenen, eloxierten oder kontrastarmen Oberflächen.',
          icon: '✈️',
        },
        {
          title: 'Einzelhandel & Bestandsmanagement',
          description: 'Inventurzählungen und Wareneingangsprozesse in Lagerräumen und Distributionszentren mit hochbewegungstoleranter Scan-Technologie beschleunigen.',
          icon: '🏬',
        },
      ],
      fr: [
        { title: 'Entrepôt & Logistique', description: 'Scannez les étiquettes au niveau du sol ou sur les rayonnages en hauteur avec le système à double objectif Z-3572, éliminant le besoin de plusieurs scanners dans une même installation.', icon: '🏭' },
        { title: 'Service de Terrain & Maintenance', description: 'Lisez les codes DPM sur les machines, tuyaux et composants dans des espaces étroits ou des conditions extérieures difficiles avec le boîtier robuste IP54 du Z-3502.', icon: '🔧' },
        { title: 'MRO Aéronautique & Défense', description: 'Suivez les pièces d\'aéronef sérialisées avec des codes DPM gravés au laser que le Z-3502 décode de manière fiable — même sur des surfaces courbes, anodisées ou à faible contraste.', icon: '✈️' },
        { title: 'Vente au Détail & Gestion des Stocks', description: 'Accélérez les inventaires et les flux de réception dans les arrière-boutiques et les centres de distribution avec une numérisation à haute tolérance de mouvement.', icon: '🏬' },
      ],
      it: [
        { title: 'Magazzino & Logistica', description: 'Scansionate etichette a livello del suolo o su scaffalature in altezza con il sistema a doppio obiettivo Z-3572, eliminando la necessità di più scanner in un\'unica struttura.', icon: '🏭' },
        { title: 'Assistenza Tecnica & Manutenzione', description: 'Leggete codici DPM su macchinari, tubi e componenti in spazi angusti o condizioni esterne difficili con la robusta custodia IP54 dello Z-3502.', icon: '🔧' },
        { title: 'MRO Aeronautica & Difesa', description: 'Tracciate parti di aeromobili serializzate con codici DPM incisi al laser che il Z-3502 decodifica in modo affidabile — anche su superfici curve, anodizzate o a basso contrasto.', icon: '✈️' },
        { title: 'Retail & Gestione Inventario', description: 'Accelerate le ricognizioni cicliche e i flussi di ricevimento nei magazzini e nei centri di distribuzione con una scansione ad alta tolleranza al movimento.', icon: '🏬' },
      ],
      es: [
        { title: 'Almacén y Logística', description: 'Escanee etiquetas a nivel del suelo o en estanterías altas con el sistema de doble lente Z-3572, eliminando la necesidad de múltiples escáneres en una misma instalación.', icon: '🏭' },
        { title: 'Servicio de Campo y Mantenimiento', description: 'Lea códigos DPM en maquinaria, tuberías y componentes en espacios reducidos o condiciones exteriores adversas con el robusto housing IP54 del Z-3502.', icon: '🔧' },
        { title: 'MRO Aeroespacial y Defensa', description: 'Rastree piezas de aeronaves serializadas con códigos DPM grabados con láser que el Z-3502 decodifica de forma fiable — incluso en superficies curvas, anodizadas o de bajo contraste.', icon: '✈️' },
        { title: 'Retail y Gestión de Inventario', description: 'Acelere los recuentos de ciclos y los flujos de trabajo de recepción en almacenes minoristas y centros de distribución con escaneo de alta tolerancia al movimiento.', icon: '🏬' },
      ],
    },
  },
];
